// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tanosnzvutxqldycwcrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRhbm9zbnp2dXR4cWxkeWN3Y3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mjc3NzU1NTUsImV4cCI6MjA0MzM1MTU1NX0.j9LPVaXf64z_Mq5OPzi1j3uJUAY6koIwHL2-uaVn6KA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);